language: node_js
node_js:
- '10'
install:
- yarn
script:
- yarn test
- yarn build
deploy:
  provider: npm
  email: dev@nathanaelcherrier.com
  api_key:
    secure: fqHbfigAEQA3KuwiaQJwoLuFjc8aL1uJ05Ob5fGrmg21KA50w2wn5Wd4+AjIbcCecvx5afK0zDyXZDbSeUs8dWMW6BbVEB22z1TQyoJxEJFB8J5jtMCWkFU4pM74tsDWIrXKxFmXId3ZkEcQexBJ/CAKuW35i5e2fSq8hYDPERRYF6eKpWZgKtcb89I/b8hKctoGpCaCLA5JvugM6RAORtXcqPRphppWGlc3kq5oMLbNdWbBp5bxRPd5IimnzIcBnqEV8rjRVvJcFz2ch34XL3RACAZeiXybX3yFOT8GUktxMCTIBHSfCgdHLgASMrFAvTHYYl9Fp4HWp7VaLtFv1I4VJ+W9KdUoqDE6tlUWIzSBZnUpDG6Dbc4vbI1uSb27MF/L2vCIN34kilvlBc71Rr0jF71Lv4tEklJZn1b3tJ+6kZCZyAZCxTcjwfmpPFbgPoQzK1gVILVRsBZ15/E0e9fl0UBfV/nZoUx+rsRXKAsdWYFiZOz7Hq1WMbeGkg6sl5JizZlHqQSia65AsYKcCP5neDPZjwI+BzQhHFeKm41HcH9U7IZfLi/thlkjgCF2cKysy/YUJgVThb6IHhg0iXi2r7BvzfITlQ+EoMbwyKlTkbjv315FyLB6mQGmEHuPub4KTuLZWYfAEs6hfhj6Sa3L4puT22YGcymxPuuVUio=
  on:
    branch: master
    tags: true
