name: Wiki CD

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init repo
      run: |
        mkdir wiki
        cd wiki
        git init
        git remote add origin https://${{ secrets.WIKI_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki.git
        git config user.email "dev@nathanaelcherrier.com"
        git config user.name "Nathanaël Cherrier (CI)"
        git pull origin master
    - name: Clean working directory
      run: |
        rm -rf wiki/*
    - name: Make wiki files from docs files
      run: |
        cp -R docs/* wiki/
        find wiki -type f -name "*.md" -print0 | xargs -0 sed -r "s/\(\.+\/?.*\/(.*)\.md\)/\(\1\)/g" -i
    - name: Deploy to GH Wiki
      run: |
        cd wiki
        git add .
        git commit -m "Update wiki after release"
        git push origin master
